### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by Hackebein** [ferret99gt/GradioMVL#7]
After running for some hours it suddenly crashed(?) and was stuck there. Clicking Stop and Start in the UI fixed it temporare.
```
Conversion took: 0.07958483695983887
Conversion took: 0.07854104042053223
Conversion took: 0.08368110656738281
Conversion took: 0.08663725852966309
Conversion took: 0.08125996589660645
Conversion took: 0.0883171558380127
Conversion took: 0.18883609771728516
Conversion took: 2.0105159282684326
Model generation logic took longer than specified latency.
Conversion took: 0.05684185028076172
conversion_process_target: stopped
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\User\Projects\GradioMVL\conversion_thread.py", line 62, in run
    out = self.voice_conversion.run(wav, HDW_FRAMES_PER_BUFFER)
  File "C:\Users\User\Projects\GradioMVL\voice_conversion.py", line 132, in run
    return self.run_linear_crossfade(wav, HDW_FRAMES_PER_BUFFER)
  File "C:\Users\User\Projects\GradioMVL\voice_conversion.py", line 154, in run_linear_crossfade
    out[-(HDW_FRAMES_PER_BUFFER + self._fade_samples) : -HDW_FRAMES_PER_BUFFER] * self._linear_fade_in
ValueError: operands could not be broadcast together with shapes (0,) (441,)
```

**Comment by Hackebein** [comment]
Input latenxy 300
Crossface Methid linear
Voice File yara

**Comment by ferret99gt** [comment]
This is probably fixed now, some recent tweaks included buffer overrun protection

**Comment by ferret99gt** [comment]
Fixed in e590ca5. Real-time queues are now bounded, stale capture/output chunks are discarded after overruns, crossfade length is clamped to the available model output, and worker-thread failures are detected. Long inference stalls may still cause an audible dropout, but should no longer crash or wedge the conversion pipeline.
