### ISSUE TITLE
Problems with Numpy

### ISSUE THREAD

**Issue by Necn0** [ferret99gt/GradioMVL#8]
I'm getting the following error when running the launch.bat:
 
"venv "C:\Users\Ephra\Desktop\GradioMVL-main\venv\Scripts\Python.exe"
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Launching GradioMVL!
We're loading the model and warming it up, please standby! Approximately 30-50 seconds!

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\Ephra\Desktop\GradioMVL-main\launch.py", line 22, in <module>
    main()
  File "C:\Users\Ephra\Desktop\GradioMVL-main\launch.py", line 18, in main
    start()
  File "C:\Users\Ephra\Desktop\GradioMVL-main\modules\launch_utils.py", line 156, in start
    mvl.start()
  File "C:\Users\Ephra\Desktop\GradioMVL-main\mvl.py", line 259, in start
    voice_conversion = ConversionPipeline(output_sample_rate)
  File "C:\Users\Ephra\Desktop\GradioMVL-main\voice_conversion.py", line 96, in __init__
    super().__init__(sample_rate)
  File "C:\Users\Ephra\Desktop\GradioMVL-main\voice_conversion.py", line 23, in __init__
    self.device = torch.device('cpu')
C:\Users\Ephra\Desktop\GradioMVL-main\voice_conversion.py:23: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  self.device = torch.device('cpu')
Loading 24K model...
Traceback (most recent call last):
  File "C:\Users\Ephra\Desktop\GradioMVL-main\launch.py", line 22, in <module>
    main()
  File "C:\Users\Ephra\Desktop\GradioMVL-main\launch.py", line 18, in main
    start()
  File "C:\Users\Ephra\Desktop\GradioMVL-main\modules\launch_utils.py", line 156, in start
    mvl.start()
  File "C:\Users\Ephra\Desktop\GradioMVL-main\mvl.py", line 260, in start
    voice_conversion.set_target("yara")
  File "C:\Users\Ephra\Desktop\GradioMVL-main\voice_conversion.py", line 52, in set_target
    self.target = torch.from_numpy(self.target).unsqueeze(0).to(self.device)
RuntimeError: Numpy is not available
Press any key to continue . . ."

Numpy is installed. I have also downgraded the version of numpy to 1.26.4. Same issue.
Any idea how to fix this?

**Comment by ferret99gt** [comment]
Updated requirements.txt to lock numpy at 1.x, as Torch 2.3 is not compatible with Numpy 2.x
